# Generated by Django 5.2.2 on 2025-06-04 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currencyrate',
            name='currency_pair',
            field=models.CharField(default='USD/RUB', max_length=10),
        ),
        migrations.AlterField(
            model_name='currencyrate',
            name='source',
            field=models.CharField(max_length=100),
        ),
    ]
